### ISSUE TITLE
Several UDDI unit tests are broken

### ISSUE THREAD

**Issue by SolidsoftReplyDevelopment** [Solidsoft-Reply/ESB-Libraries#4]
Several of the UDDI unit tests fail when run.

**Comment by SolidsoftReplyDevelopment** [comment]
This is largely related to the use of code contracts.  The code contract technology needs to be downloaded and installed.  However, when I tried this with the current version, there were several issues with constant messages stating, incorrectly, that the cc_writer was not installed.  I decided to remove code contracts from the code, replacing them with validation code.  This has improved matters.  However, some tests still fail.  This requires further investigation.

**Comment by cnayoung** [comment]
All fixed
